config:
  guestbook_name: "MyPopRock Festival 2.0"
  backend_uri: "http://backend.minikube.local/guestbook"
replicasCount: 1
service:
  name: frontend
  port: 80
  type: ClusterIP
container:
  image:
    name: phico/frontend
    tag: "2.0"
    pullPolicy: Always
  port: 4200
ingress:
  host: frontend.minikube.local
