apiVersion: v1
kind: Service
metadata:
  labels:
    name: {{ .Release.Name }}-{{ .Chart.Name }}
  name: {{ .Values.service.name }}
spec:
  ports:
    - protocol: "TCP"
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.container.port.number }}
  selector:
    app: {{ .Release.Name }}-{{ .Chart.Name }}
