apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}
spec:
  replicas: {{ .Values.replicas.count }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-{{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-{{ .Chart.Name }}
    spec:
      containers:
        - image: {{ .Values.container.image.name }}:{{ .Values.container.image.tag }}
          imagePullPolicy: {{ .Values.container.image.imagePullPolicy }}
          name: {{ .Release.Name }}-{{ .Chart.Name }}
          ports:
            - name: {{ .Values.container.port.name }}
              containerPort: {{ .Values.container.port.number }}
          env:
            - name: MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: mongodb-uri

