apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}{{ .Chart.Name }}-secret
data:
  mongodb_uri: {{ with .Values.secret.mongodb -}}
  {{- list "mongodb://" .mongodb_username ":" .mongodb_password "@" $.Release.Name "-" .db_chart ":" .db_port "/" .db_connection | join "" | b64enc | quote }}
  {{- end}}
