secret:
  mongodb:
    mongodb_username: "admin"
    mongodb_password: "password"
    db_chart: "database"
    db_port: 27017
    db_connection: "guestbook?authSource=admin"
service:
  name: backend
  port: 80
ingress:
  host: backend.minikube.local
replicas:
  count: 1
container:
  port:
    name: backend
    number: 3000
  image:
    imagePullPolicy: Always
    name: phico/backend
    tag: "2.0"
