apiVersion: v1
kind: Service
metadata:
  labels:
    name: {{ .Release.Name }}-{{ .Chart.Name }}
  name: {{ .Release.Name }}-{{ .Chart.Name }}
spec:
  ports:
    - name: {{ .Release.Name }}-{{ .Chart.Name }}
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
  selector:
    app: {{ .Release.Name }}-{{ .Chart.Name }}
  type: {{ .Values.service.type }}
