apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}-pvc
spec:
  accessModes:
    - {{ .Values.persistentVolumeClaim.permissions.accessMode }}
  resources:
    requests:
      storage: {{ .Values.persistentVolumeClaim.storage.capacity }}
